name: Deploy to EC2

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          # Redirect to service folder
          cd ~/services

          # Create public project folder if not exist
          mkdir -p public/diabetes-prediction-app

          # Download model checkpoint, scaler
          curl "https://github.com/lngquoctrung/diabetes-prediction/releases/download/v1.0.0/xgboost_model_checkpoint.pkl" -o "./public/diabetes-prediction-app/xgboost_model_checkpoint.pkl"
          curl "https://github.com/lngquoctrung/diabetes-prediction/releases/download/v1.0.0/xgb_min_max_scaler.pkl" -o "./public/diabetes-prediction-app/xgb_min_max_scaler.pkl"

          # Clone project if project folder does not exist
          if [ ! -d "diabetes-prediction-system" ]; then
            git clone -b production git@github.com:lngquoctrung/diabetes-prediction.git ~/services/diabetes-prediction-system
          fi

          # Redirect to project folder
          cd diabetes-prediction-system

          # Remove old version
          docker stop diabetes-prediction-system 2>/dev/null || true
          docker rm diabetes-prediction-system 2>/dev/null || true
          docker rmi diabetes-prediction:latest 2>/dev/null || true
          
          # Create new image and run container
          docker build --no-cache -t diabetes-prediction:latest .
          docker run -d --name diabetes-prediction-system -p 7000:7000 diabetes-prediction:latest

          # Clean cache builder
          docker builder prune -f

          # Remove root folder release memory of server
          cd ..
          rm -rf diabetes-prediction-system
        EOF
